services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: doc-pilot-postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: docpilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - docpilotdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d docpilot" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  docpilotdata: